name: itcd
version: 0.0.1
dependencies:
  angular2: 2.0.0-alpha.45
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
  angular2_material: "^2.0.0-alpha.45"
  test: any
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
